name: Build Mod
on:
  workflow_dispatch:
    inputs:
      mod_name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Mod name'
        # Default value if no value is explicitly provided
        default: 'TheOnlyCure'
        # Input has to be provided for the workflow to run
        required: true
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: mkdir -p ${{ inputs.mod_name }}
    - run: mkdir -p ${{ inputs.mod_name }}/Contents
    - run: mkdir -p ${{ inputs.mod_name }}/Contents/mods/
    - run: mkdir -p ${{ inputs.mod_name }}/Contents/mods/${{ inputs.mod_name }}

    
    - run: echo hello > ${{ inputs.mod_name}}/Contents/mods/${{ inputs.mod_name }}/world.txt
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.mod_name }} 
        path: |
          ${{ inputs.mod_name }}/Contents/mods/${{ inputs.mod_name }}
