name: Build Mod
on:
  workflow_dispatch:
    inputs:
      mod_name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Mod name'
        # Default value if no value is explicitly provided
        default: 'TheOnlyCure'
        # Input has to be provided for the workflow to run
        required: true
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: mkdir -p ${{ inputs.mod_name }}/Contents/mods/${{ inputs.mod_name }}
    - run: cp workshop.txt  ${{ inputs.mod_name }}/workshop.txt
    - run: cp mod.info ${{ inputs.mod_name }}/Contents/mods/${{ inputs.mod_name }}/mod.info
    - run: cp -r media ${{ inputs.mod_name }}/Contents/mods/${{ inputs.mod_name }}/media
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.mod_name }} 
        path: |
          ${{ inputs.mod_name }}
          ${{ inputs.mod_name }}/Contents/
          ${{ inputs.mod_name }}/Contents/mods
          ${{ inputs.mod_name }}/Contents/mods/${{ inputs.mod_name }}/*
